from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "main.ipynb"

SECTIONS = [
    ("1. How to Use This Notebook", "Run this notebook top-to-bottom from a clean environment. Standalone numerical settings are illustrative until the official S3 Challenge Kit is integrated."),
    ("2. Phase 1 Challenge Overview", "S3 is the single selected problem statement. Phase 1 ends with Processor A versus Processor B; Processor C and custom Processor D are out of scope."),
    ("3. Repository Structure", "Source code, data, processor definitions, tests, results, documentation and reporting are separated."),
    ("4. Core Mental Model", "Problem / algorithm → logical circuit → placement and routing → physical processor → measurements → problem and architecture metrics."),
    ("5. Quantum Foundations", "The demonstrator uses RZZ and RX operations in a first-order Trotter product formula. The Bell benchmark provides XX, YY and ZZ coherence checks."),
    ("6. Processor as a Graph", "A processor is physical qubits plus a coupling graph. Non-adjacent interactions require routing."),
    ("7. Bell-State Example", "The practice benchmark evaluates XX, YY and ZZ correlations for the Bell state."),
    ("8. Routing and SWAP Overhead", "Routing is derived from the coupling graph instead of hardcoded topology assumptions."),
    ("9. Transpilation", "The Qiskit adapter accepts an organizer-supplied coupling map and basis-gate definition with a fixed transpiler seed."),
    ("10. Noise", "The practice path applies stochastic Pauli errors; these rates are illustrative and are not hardware characterization."),
    ("11. Required Measurements", "Record problem quality together with depth, two-qubit gates, routing/SWAP overhead, physical qubits and uncertainty."),
    ("12. Processor Definitions", "Processor JSON files are schema-validated before use. Official definitions must declare source=official_challenge_kit."),
    ("13. Problem Statement", "Selected PS: S3 — Noise in Trotter Simulation."),
    ("14. A/B Experiment", "The same logical workload is benchmarked on the two practice processor models using deterministic seeds."),
    ("15. A/B Comparison", "Compare solution quality with circuit cost and routing overhead, then explain measured differences."),
    ("16. Protection / Error Detection", "The Bell practice benchmark includes computational-basis postselection yield. This is not the offline C/D final."),
    ("17. Scientific Reporting", "Record processor definition, circuit version, trajectory count, seed, noise assumptions, resource metrics and uncertainty."),
    ("18. Results and Figures", "Practice result tables and figures are generated by scripts and stored as machine-readable files."),
    ("19. Experience-Level Approaches", "Explorer: Bell and checks. Builder: routing and noise-aware comparison. Research: geometry-aware encodings after shortlisting."),
    ("20. Workflow Checklist", "One PS, identical workload on A/B, measured metrics, evidence-based interpretation, reproducible outputs and AI disclosure."),
    ("21. Final Experiment Structure", "Selected PS → logical workflow → Processor A → Processor B → A/B comparison → evidence-based explanation."),
    ("22. Submission Checklist", "Official submission requires exact Challenge Kit inputs, official Processor A/B definitions, clean execution, results, report, graphs and repository accessibility."),
    ("23. Participant Lab Notes", "Document workload, routing changes, measured evidence, architecture effects and remaining uncertainty."),
]


def markdown(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(True)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": text.splitlines(True),
    }


def build() -> None:
    cells = [
        markdown("# Qiskit Fall Fest 2026 — Phase 1\n## S3: Noise in Trotter Simulation\n"),
        code("from pathlib import Path\nROOT = Path.cwd()\n"),
    ]

    for title, description in SECTIONS:
        cells.append(markdown(f"## {title}\n\n{description}\n"))

        if title.startswith("7."):
            cells.append(code(
                "from src.bell_benchmark import bell_state, bell_correlations, fidelity_to_bell, bell_density\n"
                "state = bell_state()\n"
                "print(bell_correlations(state))\n"
                "print('Bell fidelity:', fidelity_to_bell(bell_density()))\n"
            ))
        elif title.startswith("8."):
            cells.append(code(
                "import json\n"
                "from src.processors import interaction_swap_count\n"
                "cfg = json.loads((ROOT / 'processors' / 'processor_B.json').read_text())\n"
                "swaps = interaction_swap_count(tuple(map(tuple, cfg['coupling_map'])), cfg['num_qubits'], cfg['ports'][0], cfg['ports'][1])\n"
                "print('Illustrative B routing swaps:', swaps)\n"
            ))
        elif title.startswith("12."):
            cells.append(code(
                "import json\n"
                "from src.processors import validate_processor_definition\n"
                "for label in ('A', 'B'):\n"
                "    definition = json.loads((ROOT / 'processors' / f'processor_{label}.json').read_text())\n"
                "    validate_processor_definition(definition, label)\n"
                "    print(label, definition['name'])\n"
            ))
        elif title.startswith("14."):
            cells.append(code(
                "import json\n"
                "from src.practice_s3 import PracticeProcessor, benchmark_processor, ideal_exact_state, logical_trotter_circuit\n"
                "cfg = json.loads((ROOT / 'data' / 'practice_config.json').read_text())\n"
                "s = cfg['system']\n"
                "logical = logical_trotter_circuit(s['trotter_steps'], s['total_time'], s['J'], s['h'])\n"
                "exact = ideal_exact_state(s['n_qubits'], s['total_time'], s['J'], s['h'])\n"
                "for key, offset in (('A', 0), ('B', 1)):\n"
                "    p = cfg['processors'][key]\n"
                "    model = PracticeProcessor(p['name'], s['n_qubits'], tuple(tuple(e) for e in p['coupling_map']), p['p1'], p['p2'], p['readout_error'])\n"
                "    result = benchmark_processor(model, logical, exact, s['n_qubits'], int(cfg['shots_or_trajectories']), int(cfg['seed']) + offset)\n"
                "    print(key, result)\n"
            ))
        elif title.startswith("15."):
            cells.append(code(
                "import pandas as pd\n"
                "table = ROOT / 'results' / 'tables' / 'practice_ab_comparison.csv'\n"
                "print(pd.read_csv(table) if table.is_file() else 'Run scripts/run_practice.py before displaying saved results.')\n"
            ))
        elif title.startswith("18."):
            cells.append(code(
                "for folder in (ROOT / 'results' / 'tables', ROOT / 'results' / 'figures'):\n"
                "    print(folder)\n"
                "    for path in sorted(folder.glob('*')):\n"
                "        print(' -', path.name)\n"
            ))
        elif title.startswith("22."):
            cells.append(code(
                "print('Practice validation: python scripts/validate_submission.py --practice')\n"
                "print('Official validation: python scripts/validate_submission.py --official')\n"
            ))

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    OUTPUT.write_text(json.dumps(notebook, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build()
